### ISSUE TITLE
Switching from ProgressView causes a crash on iPad

### ISSUE THREAD

**Issue by sboddeus** [mattgallagher/CwlViews#7] opened 2019-05-16 13:26 UTC
When showing both master (catalog) and detail views simultaneously (on iPad for example) there is a crash when switching between ProgressView and any other catalog item. This crash does not occur on iPhone screen sizes (when master and detail can not both be shown).
Seems to be an issue with `.lifetimes[]` being deallocated at the incorrect time????

"Fatal error: Attempted to read an unowned reference but the object was already deallocated2019-05-16 15:24:24.258456+0200 CwlViewsCatalog_iOS[63725:6338094] Fatal error: Attempted to read an unowned reference but the object was already deallocated"

Unfortunately with the limited time I had today I could not investigate further.

**Comment by mattgallagher** [comment] 2019-05-16 15:04
I've reproduced the issue. I think the last value from the timer might still be in transit after the `lifetimes` binding is cancelled. I'll deal with this tomorrow.

**Comment by mattgallagher** [comment] 2019-05-17 12:39
The bug was in CwlSignal... asynchronously delivered values were continuing to be delivered after cancellation. The `unowned` capture in the `subscribe` closure of the `Signal.apply(_:_)` function in CwlDynamic.swift relies on cancellation stopping all future deliveries so these after-cancellation values were triggering the fatal error.

Turns out I accidentally deleted some necessary code in CwlSignal in January while cleaning up a related problem. I've restored the deleted code and merged into CwlViews cb6269c059a89782abeec86932b8b8f039ee9512.

**Closed as completed by mattgallagher** 2019-05-17 12:39 UTC
